// Export all functions from json-db
export {
  getDatabase,
  initDatabase,
  closeDatabase,
  saveDatabase,
  generateUniqueId,
  addEnvironment,
  updateEnvironment,
  deleteEnvironment,
  addCollection,
  updateCollection,
  deleteCollection,
  addFolder,
  updateFolder,
  deleteFolder,
  addRequest,
  addRequestAfter,
  updateRequest,
  deleteRequest,
  addRequestHistory,
  deleteRequestHistory,
  setSetting,
  getSetting,
  getAllSettings,
  resetSettings,
  addUnsavedRequest,
  updateUnsavedRequest,
  deleteUnsavedRequest,
  getAllUnsavedRequests,
  clearUnsavedRequests,
  promoteUnsavedRequest,
  type UnsavedRequest,
} from './json-db';
