// Export all functions from json-db
export {
  getDatabase,
  initDatabase,
  closeDatabase,
  saveDatabase,
  generateUniqueId,
  addEnvironment,
  updateEnvironment,
  deleteEnvironment,
  addCollection,
  updateCollection,
  deleteCollection,
  addFolder,
  addFolderAfter,
  updateFolder,
  reorderFolder,
  reorderRequest,
  deleteFolder,
  addRequest,
  addRequestAfter,
  updateRequest,
  deleteRequest,
  addRequestHistory,
  deleteRequestHistory,
  clearAllRequestHistory,
  setSetting,
  getSetting,
  getAllSettings,
  resetSettings,
  addUnsavedRequest,
  updateUnsavedRequest,
  deleteUnsavedRequest,
  getAllUnsavedRequests,
  clearUnsavedRequests,
  promoteUnsavedRequest,
  addPreset,
  getAllPresets,
  deletePreset,
  type UnsavedRequest,
} from './json-db';
