// Export all functions from json-db
export {
  getDatabase,
  initDatabase,
  closeDatabase,
  saveDatabase,
  addEnvironment,
  updateEnvironment,
  deleteEnvironment,
  addCollection,
  updateCollection,
  deleteCollection,
  addFolder,
  updateFolder,
  deleteFolder,
  addRequest,
  updateRequest,
  deleteRequest,
  addRequestHistory,
  deleteRequestHistory,
  setSetting,
  getSetting,
  getAllSettings,
  resetSettings,
} from './json-db';
