import { describe, expect, it } from 'vitest';
import { generateCurlCommand } from '../../../../electron/lib/curl-generator';

describe('generateCurlCommand', () => {
  it('should generate a basic GET request', () => {
    const request = {
      method: 'GET' as const,
      url: 'https://api.example.com/users',
      headers: {},
      body: '',
      queryParams: [],
      auth: { type: 'none' as const }
    };
    const curl = generateCurlCommand(request);
    expect(curl).toBe("curl https://api.example.com/users");
  });

  it('should generate a GET request with query parameters', () => {
    const request = {
      method: 'GET' as const,
      url: 'https://api.example.com/users',
      headers: {},
      body: '',
      queryParams: [
        { key: 'page', value: '1', enabled: true },
        { key: 'limit', value: '10', enabled: true },
        { key: 'disabled', value: 'true', enabled: false }
      ],
      auth: { type: 'none' as const }
    };
    const curl = generateCurlCommand(request);
    expect(curl).toBe("curl 'https://api.example.com/users?page=1&limit=10'");
  });

  it('should generate a POST request with headers and a JSON body', () => {
    const request = {
      method: 'POST' as const,
      url: 'https://api.example.com/users',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: '{"name": "John Doe"}',
      queryParams: [],
      auth: { type: 'none' as const }
    };
    const curl = generateCurlCommand(request);
    expect(curl).toContain("curl -X POST https://api.example.com/users");
    expect(curl).toContain("-H 'Content-Type: application/json'");
    expect(curl).toContain("-H 'Accept: application/json'");
    expect(curl).toContain("--data-raw '{\"name\": \"John Doe\"}'");
  });

  it('should handle bearer token authentication', () => {
    const request = {
      method: 'GET' as const,
      url: 'https://api.example.com/secure',
      headers: {
        'authorization': 'Bearer OLD_TOKEN' // Should be overridden or ignore old if auth is used
      },
      body: '',
      queryParams: [],
      auth: { type: 'bearer' as const, token: 'MY_SECRET_TOKEN' }
    };
    const curl = generateCurlCommand(request);
    // The previous implementation skips 'authorization' header if it's generated by auth type
    expect(curl).not.toContain("OLD_TOKEN");
    expect(curl).toContain("-H 'Authorization: Bearer MY_SECRET_TOKEN'");
  });

  it('should handle basic authentication', () => {
    const request = {
      method: 'GET' as const,
      url: 'https://api.example.com/secure',
      headers: {},
      body: '',
      queryParams: [],
      auth: { type: 'basic' as const, username: 'admin', password: 'password123' }
    };
    const curl = generateCurlCommand(request);
    expect(curl).toContain("-u admin:password123");
  });

  it('should handle API key authentication', () => {
    const request = {
      method: 'GET' as const,
      url: 'https://api.example.com/secure',
      headers: {},
      body: '',
      queryParams: [],
      auth: { type: 'apikey' as const, apiKey: 'KEY123', apiKeyHeader: 'X-Api-Key' }
    };
    const curl = generateCurlCommand(request);
    expect(curl).toContain("-H 'X-Api-Key: KEY123'");
  });

  it('should generate a POST request with form-data', () => {
    const request = {
      method: 'POST' as const,
      url: 'https://api.example.com/upload',
      headers: {},
      body: '',
      bodyType: 'form-data',
      bodyFormData: [
        { key: 'username', value: 'john', enabled: true },
        { key: 'avatar', value: 'FILE::/path/to/image.png', enabled: true },
        { key: 'disabled', value: 'nope', enabled: false }
      ],
      queryParams: [],
      auth: { type: 'none' as const }
    };
    const curl = generateCurlCommand(request);
    expect(curl).toContain("-F 'username=john'");
    expect(curl).toContain("'avatar=@/path/to/image.png'");
  });

  it('should generate a POST request with x-www-form-urlencoded', () => {
    const request = {
      method: 'POST' as const,
      url: 'https://api.example.com/submit',
      headers: {},
      body: '',
      bodyType: 'x-www-form-urlencoded',
      bodyFormData: [
        { key: 'name', value: 'John Doe', enabled: true },
        { key: 'age', value: '30', enabled: true }
      ],
      queryParams: [],
      auth: { type: 'none' as const }
    };
    const curl = generateCurlCommand(request);
    expect(curl).toContain("--data-urlencode 'name=John Doe'");
    expect(curl).toContain("--data-urlencode 'age=30'");
  });

  it('should properly escape shell strings with single quotes', () => {
    const request = {
      method: 'POST' as const,
      url: 'https://api.example.com/test',
      headers: {},
      body: "It's a test",
      queryParams: [],
      auth: { type: 'none' as const }
    };
    const curl = generateCurlCommand(request);
    expect(curl).toContain("--data-raw 'It'\\''s a test'");
  });

  it('should generate a multi-line curl command for long outputs', () => {
    const request = {
      method: 'POST' as const,
      url: 'https://api.example.com/very/long/url/that/will/exceed/80/characters/easily/and/trigger/multiline',
      headers: {
        'X-My-Long-Header': 'This is a very long header value that will definitely cause wrapping'
      },
      body: '{"data": "much more data"}',
      queryParams: [],
      auth: { type: 'none' as const }
    };
    const curl = generateCurlCommand(request);
    expect(curl.split('\n').length).toBeGreaterThan(1);
    expect(curl).toContain("curl -X POST \\");
  });
});
